image: gitpod/workspace-full

tasks:
  - name: Setup Datavzrd
    init: |
      echo "setup tutorial environment, please wait..."
      rm -rf * # clean up workspace
      mkdir data
      curl -L https://raw.githubusercontent.com/datavzrd/datavzrd/main/.examples/data/movies.csv > data/movies.csv
      curl -L https://raw.githubusercontent.com/datavzrd/datavzrd/main/.examples/data/oscars.csv > data/oscars.csv
      ("${SHELL}" <(curl -L micro.mamba.pm/install.sh) < /dev/null) &> /tmp/log-setup-micromamba.txt
      source ~/.bashrc &> /tmp/log-source-bashrc.txt
      micromamba create -n datavzrd -c conda-forge datavzrd --yes &> /tmp/log-setup-datavzrd.txt
      echo "done, ready to go!"
    command: |
      micromamba activate datavzrd
