image: gitpod/workspace-full

tasks:
  - name: Setup Datavzrd
    init: |
      echo "setup Datavzrd..."
      ("${SHELL}" <(curl -L micro.mamba.pm/install.sh) < /dev/null) &> /tmp/log-setup-micromamba.txt
      source ~/.bashrc &> /tmp/log-source-bashrc.txt
      micromamba create -n datavzrd -c conda-forge datavzrd --yes &> /tmp/log-setup-datavzrd.txt
      echo "done"
    command: |
      micromamba activate datavzrd
