image: gitpod/workspace-full

tasks:
  - name: Setup Datavzrd
    init: |
      "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      source ~/.bashrc
      micromamba create -n datavzrd -c conda-forge datavzrd
    command: |
      micromamba activate datavzrd
