image: gitpod/workspace-full

tasks:
  - name: Setup Datavzrd
    before: |
      "${SHELL}" <(curl -L micro.mamba.pm/install.sh) < /dev/null
      source ~/.bashrc
      micromamba create -n datavzrd -c conda-forge datavzrd --yes
    command: |
      micromamba activate datavzrd
