project:
  name: Datavzrd
  copyright: 2024, Koesterlab
  authors: Felix Wiegand, Johannes Koester

color: blue
logo:
  dark: datavzrd.svg # add a logo
  light: datavzrd.svg # add a logo

repo: 
  name: datavzrd/datavzrd
  contributors:
    skip:
      - github-actions[bot]
      - dependabot[bot]

header:
  logo: datavzrd.svg
  name: Datavzrd
  links:
    - text: Github
      url: https://github.com/datavzrd
    - text: Live-Preview
      url: https://datavzrd.github.io/datavzrd/index.html

hero:
  img: datavzrd.svg # add a logo
  statements:
    - A low-code interactive reporting tool for tabular datasets
  links: []

features:
  - title: Heatmaps
    desc: |
       Datavzrd makes it easy to create heatmaps from tabular data.
    code: |
      !Rated!:
        !plot!:
          !heatmap!:
            !scale!: %ordinal%
            !color-scheme!: %tableau20%

  - title: Datasets
    desc: |
        Organize your datasets in a single place with few lines of code. Use links to connect them and make your reports interactive.
    code: |
      !datasets!:
        !table-a!:
          !path!: %"table-a.csv"%
          !links!:
            !gene details!:
              !column!: %gene%
              !view!: %"gene-{value}"%
            !gene expression!:
              !column!: %gene%
              !table-row!: %table-b/gene%

  - title: Linkouts
    desc: |
        Add links to external resources to your reports to provide additional information.
    code: |
      !Gene!:
        !link-to-url!:
          !ncbi!:
            !url!: %"https://www.ncbi.nlm.nih.gov/gene/{gene}"%
      

docs:
  src: docs
  sidebar-links: []