project:
  name: Datavzrd
  version: 2.43.1
  copyright: 2024, Koesterlab
  authors: Felix Wiegand, Johannes Koester

color: blue
logo:
  dark: datavzrd_logo_white.svg # add a logo
  light: datavzrd_logo_black.svg # add a logo

repo: 
  name: datavzrd/datavzrd
  contributors:
    skip:
      - github-actions[bot]
      - dependabot[bot]

header:
  logo: datavzrd_white.svg
  name: Datavzrd
  links:
    - text: Github
      url: https://github.com/datavzrd
    - text: Live-Preview
      url: https://datavzrd.github.io/datavzrd/index.html

hero:
  img: 
    dark: datavzrd_white.svg
    light: datavzrd_white.svg
  statements:
    - A zero/low-code, interactive, visual, server-free, browser-based reporting tool for tabular datasets
  links: 
    - url: https://datavzrd.github.io/datavzrd/oscars/index_1.html
      text: Check Live Demo
    - url: https://datavzrd.github.io/docs/tutorial.html
      text: Tutorial

features:
  - title: Easily configurable interactive reports
    desc: |
      With exponentially growing gathered data per year, its representation becomes more important than ever to make it comprehensible and interpretable for humans.
      Datavzrd aims to create a solution for reporting tabular data in a sharable format that is highly customizable and easy to use with simple configuration using the yaml syntax.
    img: preview.png
    img-width: min(30vw, 550px)
    url: https://datavzrd.github.io/datavzrd/movies/index_1.html

  - title: Datasets
    desc: |
        Organize your datasets in a single place with few lines of code. Use links to connect them and make your reports interactive. 
    code: |
      !datasets!:
        !table-a!:
          !path!: %table-a.csv%
          !links!:
            !gene! !details!:
              !column!: %gene%
              !view!: %gene-{value}%
            !gene! !expression!:
              !column!: %gene%
              !table-row!: %table-b/gene%

  - title: Linkouts
    desc: |
        Add links to external resources to your reports to provide additional information and context.
    code: |
      !Gene!:
        !link-to-url!:
          !ncbi!:
            !url!: %https://www.ncbi.nlm.nih.gov/gene/{gene}%
            
  - title: Heatmaps
    desc: |
       Datavzrd makes it easy to create heatmaps from tabular data. Heatmaps can be used for numerical or categorical data with predefined color schemes or continuous color scales.
    code: |
      !Rated!:
        !plot!:
          !heatmap!:
            !scale!: %ordinal%
            !color-scheme!: %tableau20%
            
  - title: Plots
    desc: |
       Use custom vega-lite json specs to create any plot suitable for your needs or rely on Datavzrds easy to configure plot or bar plots.
    code: |
      !age!:
        !plot!:
          !ticks!:
            !scale!: %linear%
            !domain!:
              - %20%
              - %100%
              
  - title: Spells
    desc: |
       Datavzrd offers so called spells to simplify the process of creating reports by allowing users to define common configurations in a modular way. 
    code: |
      !render-table!:
        !columns!:
          !p-value!:
            !spell!:
              !url!: %v1.0.0/stats/p-value%
              !with!:
                !significance_threshold!: %0.05%

  
      
docs:
  src: docs
  links:
    Homepage: https://datavzrd.github.io
