name: Generate Spell Documentation

on:
  schedule:
    - cron: '0 17 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3

    - name: Clone the datavzrd-spells repository
      run: |
        git clone https://github.com/datavzrd/datavzrd-spells.git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML for parsing YAML
      run: |
        python -m pip install pyyaml gitpython

    - name: Generate spell documentation
      run: |
        python scripts/generate_docs.py


    - name: Check for changes to spells.rst
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/docs/spells.rst
        git diff --cached --exit-code || git commit -m "Auto-generate spell documentation"

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
